baseURL: https://sno0owp.netlify.app/
title: snow's blog

languageCode: ko-kr
DefaultContentLanguage: ko  # Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
hasCJKLanguage: true

googleAnalytics: G-KT1233XP5V
enableRobotsTXT: true

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

# staticDir:
#   - assets

summaryLength: 20

ignoreFiles:
  - project/*

module:
  hugoVersion:
    extended: true
    min: 0.87.0

markup:
  goldmark:
   extensions:
     table: true
     strikethrough: true
     linkify: false
     taskList: true
     definitionList: true
     footnote: true
   parser:
     attribute:
       block: false
       title: true
     autoHeadingID: false
     autoHeadingIDType: github
   renderer:
     hardWraps: false
     unsafe: false
   tableOfContents:
     endLevel: 3
     ordered: false
     startLevel: 2
   mathjax:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    noHl: true
    style: dracula
    tabWidth: 4

params:
  author: Seungho Park
  description: Strive to become a Software Engineer Specialist in Working & Growing Together for Reformation Technology.
  github: sno0ow-p
  # facebook:
  # twitter:
  linkedin: https://www.linkedin.com/in/sno0ow/
  # instagram:
  # tumblr:
  email: sinabro2dev@gmail.com
  # url:
  # keywords: sample keywords
  rss: false
  lastmod: true
  favicon: "/images/avatar.png"
  location: Korea
  userStatusEmoji: ðŸ™‚
  # links:
  #   - title: link A
  #     href: https://github.com/joonparkhere
  #   - title: link B
  math: true

frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default

#related:
#  includeNewer: true
#  threshold: 30
#  toLower: false
#  indices:
#    - name: tags
#      weight: 100
#    - name: categories
#      weight: 200
